#include "debug.h"
#include <inttypes.h>
#include <pico.h>
#include <stdio.h>

typedef struct __attribute__((packed)) StateFrame
{
  uint32_t r0;
  uint32_t r1;
  uint32_t r2;
  uint32_t r3;
  uint32_t r12;
  uint32_t lr;
  uint32_t pc;
  uint32_t psr;
} StateFrame;

__attribute__((optimize("O0"))) void the_real_fault_handler_c(const StateFrame *frame)
{
  printf("R0       = 0x%08" PRIx32 "\n", frame->r0);
  printf("R1       = 0x%08" PRIx32 "\n", frame->r1);
  printf("R2       = 0x%08" PRIx32 "\n", frame->r2);
  printf("R3       = 0x%08" PRIx32 "\n", frame->r3);
  printf("R12      = 0x%08" PRIx32 "\n", frame->r12);
  printf("LR [R14] = 0x%08" PRIx32 " subroutine call return address\n", frame->lr);
  printf("PC [R15] = 0x%08" PRIx32 " program counter address\n", frame->pc);
  printf("PSR      = 0x%08" PRIx32 "\n", frame->psr);

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  // ICSR - Interrupt control and status register 0x0ed04

  const uint32_t icsr = { *(volatile uint32_t *)0xE000ED04 };
  if (0 != icsr) printf("ICSR  = 0x%08" PRIx32 " (interrupt control and status register)\n", icsr);
  if (icsr & 1u << 31) printf("  PENDNMISET: exception is pending\n");
  if (icsr & 1u << 30) printf("  PENDNMICLR: allows the NMI exception pend state to be cleared\n");
  if (icsr & 1u << 28) printf("  PENDSVSET: PendSV `FTSSS exception is pending\n");
  if (icsr & 1u << 27) printf("  PENDSVCLR: allows the PendSV exception pend state to be cleared `FTSSS\n");
  if (icsr & 1u << 26) printf("  PENDSTSET: SysTick `FTSSS exception is pending\n");
  if (icsr & 1u << 25) printf("  PENDSTCLR: allows the SysTick exception pend state to be cleared `FTSSS\n");
  if (icsr & 1u << 24)
    printf("  STTNS: Controls whether in a single SysTick implementation, the SysTick is Secure or Non-secure\n");
  if (icsr & 1u << 23) printf("  ISRPREEMPT: pending exception will be serviced on exit from debug halt state\n");
  if (icsr & 1u << 22) printf("  ISRPENDING: external interrupt, generated by the NVIC, is pending\n");
  if (0 != icsr)
    printf("  VECTPENDING = 0x%08" PRIx32 " exception number of the highest priority pending and enabled interrupt\n", icsr & (0b111111111 << 12));
  if (icsr & 1u << 11) printf("  RETTOBASE: in Handler mode, indicates whether there is more than one active exception\n");
  if (0 != icsr)
    printf("  VECTACTIVE  = 0x%08" PRIx32 " exception number of the current executing exception\n", icsr & (0b111111111 << 0));

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  // SHCSR - SystemHandlerControl state register 0xE000ED24
  const uint32_t shcsr = { *(volatile uint32_t *)0xE000ED24 };
  if (0 != shcsr) printf("SHCSR = %08" PRIx32 " (SystemHandler control and state register)\n", shcsr);
  if (shcsr & 1u << 21) printf("  HARDFAULTPENDED: HardFault exception pended state\n");
  if (shcsr & 1u << 18) printf("  USGFAULTENA: UsageFault enable\n");
  if (shcsr & 1u << 17) printf("  BUSFAULTENA: BusFault enable\n");
  if (shcsr & 1u << 16) printf("  MEMFAULTENA: MemManage enable\n");
  if (shcsr & 1u << 15) printf("  SVCALLPENDED: SVCall pending\n");
  if (shcsr & 1u << 14) printf("  BUSFAULTPENDED: BusFault exception pending.\n");
  if (shcsr & 1u << 13) printf("  MEMFAULTPENDED: MemManage exception pending\n");
  if (shcsr & 1u << 12) printf("  USGFAULTPENDED: UsageFault exception pending\n");
  if (shcsr & 1u << 11) printf("  SYSTICKACT: SysTick exception active\n");
  if (shcsr & 1u << 10) printf("  PENDSVACT: PendSV exception active\n");
  if (shcsr & 1u << 8) printf("  MONITORACT: Debug monitor active\n");
  if (shcsr & 1u << 7) printf("  SVCALLACT: SVCall active\n");
  if (shcsr & 1u << 5) printf("  NMIACT: NMI exception active state\n");
  if (shcsr & 1u << 3) printf("  USGFAULTACT: UsageFault exception active\n");
  if (shcsr & 1u << 2) printf("  HARDFAULTACT: HardFault exception active\n");
  if (shcsr & 1u << 1) printf("  BUSFAULTACT: BusFault exception active\n");
  if (shcsr & 1u << 0) printf("  MEMFAULTACT: MemManage exception active\n");

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  // MMFSR - MemoryManagement fault Status register 0xE000ED28
  const volatile uint8_t mmfsr = { *(volatile uint8_t *)0xE000ED28 };
  if (0 != mmfsr) printf("MMFSR = 0x%02" PRIx8 " (MemManage fault status register)\n", mmfsr);
  if (mmfsr & 1u << 7) printf("  MMARVALID: MMFAR holds a valid fault address\n");
  if (mmfsr & 1u << 5) printf("  MLSPERR: MemManage fault occurred during floating-point lazy state preservation\n");
  if (mmfsr & 1u << 4) printf("  MSTKERR: stacking for an exception entry has caused one or more access violations\n");
  if (mmfsr & 1u << 3) printf("  MUNSTKERR: unstack for an exception return has caused one or more access violations\n");
  if (mmfsr & 1u << 1) printf("  DACCVIOL: attempt to load/store at location that does not permit the operation\n");
  if (mmfsr & 1u << 0) printf("  IACCVIOL: attempted an instruction fetch from location that does not permit execution\n");

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  // BFSR - BusFault status register 0xE000ED29
  const uint8_t bfsr = { *(volatile unsigned char *)0xE000ED29 };
  if (0 != bfsr) printf("BFSR  = 0x%02" PRIx8 " (BusFault status register)\n", bfsr);
  if (bfsr & 1u << 7) printf("  BFARVALID: BFAR holds a valid fault address\n");
  if (bfsr & 1u << 5) printf("  LSPERR: bus fault occurred during floating-point lazy state preservation\n");
  if (bfsr & 1u << 4) printf("  STKERR: stacking for an exception entry has caused one or more BusFaults\n");
  if (bfsr & 1u << 3) printf("  UNSTKERR: unstack for an exception return has caused one or more BusFaults\n");
  if (bfsr & 1u << 2) printf("  IMPREISERR: imprecise data access violation\n");
  if (bfsr & 1u << 1)
    printf("  PRECISERR: PC value stacked for the exception return points to the instruction that caused fault\n");
  if (bfsr & 1u << 0) printf("  IBUSERR: instruction bus error\n");

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  // UFSR - UsageFault status register 0xE000ED2A
  const uint16_t ufsr = { *(volatile uint16_t *)0xE000ED2A };
  if (0 != ufsr) printf("UFSR  = 0x%04" PRIx16 " (UsageFault status register)\n", ufsr);
  if (ufsr & 1u << 9) printf("  DIVBYZERO: executed an SDIV or UDIV with a divisor 0\n");
  if (ufsr & 1u << 8) printf("  UNALIGNED: unaligned memory access\n");
  if (ufsr & 1u << 4) printf("  STKOF: stack overflow error has occurred\n");
  if (ufsr & 1u << 3) printf("  NOCP: attempt to access a coprocessor\n");
  if (ufsr & 1u << 2)
    printf(
      "  INVPC: attempted an illegal load of EXC_RETURN to the PC (either invalid context or an invalid EXC_RETURN value)\n");
  if (ufsr & 1u << 1) printf("  INVSTATE: attempt to execute instruction that makes illegal use of the EPSR\n");
  if (ufsr & 1u << 0) printf("  UNDEFINSTR: attempt to execute an undefined instruction\n");

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  // HFSR - HardFault status register 0xE000ED2C
  const uint32_t hfsr = { *(volatile uint32_t *)0xE000ED2C };
  if (0 != hfsr) printf("HFSR  = 0x%08" PRIx32 " (HardFault status register)\n", hfsr);
  if (hfsr & 1u << 31) printf("  DEBUGEVT: hard fault caused by debug event\n");
  if (hfsr & 1u << 30) printf("  FORCED: forced hard fault escalation caused by bus/memory-management/usage fault\n");
  if (hfsr & 1u << 1) printf("  VECTTBL: hard fault caused by failed vector-table read\n");

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  const uint32_t mmfar = {*((volatile uint32_t *)(0xE000ED34))};
  if (mmfsr & 1u << 7) printf("MMFAR = 0x%08" PRIx32 " memory fault address\n", mmfar);
  const uint32_t bfar = {*(volatile uint32_t *)0xE000ED38};
  if (bfsr & 1u << 7) printf("BFAR  = 0x%08" PRIx32 " bus fault address\n", bfar);

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en
  // AFSR - AuxilarityFault status register
  const uint32_t afsr = { *(volatile uint32_t *)0xE000ED3C };
  if (0 != afsr) printf("AFSR = 0x%08" PRIx32 "\n", afsr);

  printf("C%dE HardFault handler: waiting for debugger ...\n", get_core_num());

  fflush(stdout);
  // if debugger attached
  // if ((*(volatile uint32_t *)0xE000EDF0) & (1 << 0)) __breakpoint();;
  while (1) {
    __breakpoint();
  }
}

void isr_hardfault()
{
  printf("\nC%dE HardFault handler ...\n", get_core_num());
  __asm volatile("tst lr, #4 \n"
                 "ite eq \n"
                 "mrseq r0, msp \n"
                 "mrsne r0, psp \n"
                 "b the_real_fault_handler_c \n");
}
