#include "debug.h"
#include <hardware/structs/m33.h>
#include <inttypes.h>
#include <pico.h>
#include <stdio.h>

/// How to debug a HardFault on an ARM Cortex-M MCU
/// Shamelessly stolen here: https://interrupt.memfault.com/blog/cortex-m-hardfault-debug

typedef struct __attribute__((packed)) StateFrame
{
  uint32_t r0;
  uint32_t r1;
  uint32_t r2;
  uint32_t r3;
  uint32_t r12;
  uint32_t lr;
  uint32_t pc;
  uint32_t psr;
} StateFrame;

// A fault caused by an exhausted stack cannot safely call C code on that same
// stack. Keep a separate stack for each core so simultaneous faults cannot
// corrupt each other's diagnostics.
static uint32_t hardfault_stacks[NUM_CORES][256] __attribute__((aligned(8), used));

[[noreturn]]
__attribute__((optimize("O0"))) void the_real_fault_handler_c(StateFrame *frame)
{
  const uint32_t cfsr = m33_hw->cfsr;

  printf("\nC%dE HardFault handler ...\n", get_core_num());

  if (cfsr & M33_CFSR_UFSR_STKOF_BITS)
  {
    // Exception stacking is not reliable after an MSPLIM/PSPLIM violation.
    printf("Exception frame unavailable because the stack overflowed\n");
  }
  else
  {
    // core registers: https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Processor/Programmer-s-model/Core-registers?lang=en
    printf("R0      = 0x%08" PRIx32 " MSP/PSP\n", frame->r0);
    printf("R1      = 0x%08" PRIx32 "\n", frame->r1);
    printf("R2      = 0x%08" PRIx32 "\n", frame->r2);
    printf("R3      = 0x%08" PRIx32 "\n", frame->r3);
    printf("R12     = 0x%08" PRIx32 "\n", frame->r12);
    printf("LR[R14] = 0x%08" PRIx32 " subroutine call return address\n", frame->lr);
    printf("PC[R15] = 0x%08" PRIx32 " program counter address\n", frame->pc);
    // xPSR https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Processor/Programmer-s-model/Core-registers/Combined-Program-Status-Register?lang=en
    printf("xPSR    = 0x%08" PRIx32 " combined status register (APSR, EPSR, IPSR)\n", frame->psr);
  }

  // https://developer.arm.com/documentation/100235/0100/The-Cortex-M33-Peripherals/System-Control-Block/System-control-block-registers-summary?lang=en

  // ICSR - interrupt control and status register
  if (m33_hw->icsr) printf("ICSR  = 0x%08" PRIx32 " (interrupt control and status register)\n", m33_hw->icsr);
  if (m33_hw->icsr & M33_ICSR_PENDNMISET_BITS) printf("  PENDNMISET: exception is pending\n");
  if (m33_hw->icsr & M33_ICSR_PENDNMICLR_BITS) printf("  PENDNMICLR: allows the NMI exception pend state to be cleared\n");
  if (m33_hw->icsr & M33_ICSR_PENDSVSET_BITS) printf("  PENDSVSET: PendSV `FTSSS exception is pending\n");
  if (m33_hw->icsr & M33_ICSR_PENDSVCLR_BITS)
    printf("  PENDSVCLR: allows the PendSV exception pend state to be cleared `FTSSS\n");
  if (m33_hw->icsr & M33_ICSR_PENDSTSET_BITS) printf("  PENDSTSET: SysTick `FTSSS exception is pending\n");
  if (m33_hw->icsr & M33_ICSR_PENDSTCLR_BITS)
    printf("  PENDSTCLR: allows the SysTick exception pend state to be cleared `FTSSS\n");
  if (m33_hw->icsr & 1u << 24)
    printf("  STTNS: Controls whether in a single SysTick implementation, the SysTick is Secure or Non-secure\n");
  if (m33_hw->icsr & M33_ICSR_ISRPREEMPT_BITS)
    printf("  ISRPREEMPT: pending exception will be serviced on exit from debug halt state\n");
  if (m33_hw->icsr & M33_ICSR_ISRPENDING_BITS) printf("  ISRPENDING: external interrupt, generated by the NVIC, is pending\n");
  if (m33_hw->icsr & M33_ICSR_VECTPENDING_BITS)
    printf(
      "  VECTPENDING = 0x%08" PRIx32 " exception number of the highest priority pending and enabled interrupt\n",
      (m33_hw->icsr & M33_ICSR_VECTPENDING_BITS) >> M33_ICSR_VECTPENDING_LSB);
  if (m33_hw->icsr & M33_ICSR_RETTOBASE_BITS)
    printf("  RETTOBASE: in Handler mode, indicates whether there is more than one active exception\n");
  if (m33_hw->icsr & M33_ICSR_VECTACTIVE_BITS)
    printf("  VECTACTIVE  = 0x%08" PRIx32 " exception number of the current executing exception\n", (m33_hw->icsr & M33_ICSR_VECTACTIVE_BITS) >> M33_ICSR_VECTACTIVE_LSB);

  // SHCSR - system handler control state register 0xE000ED24
  if (m33_hw->shcsr) printf("SHCSR = %08" PRIx32 " (SystemHandler control and state register)\n", m33_hw->shcsr);
  if (m33_hw->shcsr & M33_SHCSR_HARDFAULTPENDED_BITS) printf("  HARDFAULTPENDED: HardFault exception pended state\n");
  if (m33_hw->shcsr & M33_SHCSR_USGFAULTENA_BITS) printf("  USGFAULTENA: UsageFault enable\n");
  if (m33_hw->shcsr & M33_SHCSR_BUSFAULTENA_BITS) printf("  BUSFAULTENA: BusFault enable\n");
  if (m33_hw->shcsr & M33_SHCSR_MEMFAULTENA_BITS) printf("  MEMFAULTENA: MemManage enable\n");
  if (m33_hw->shcsr & M33_SHCSR_SVCALLPENDED_BITS) printf("  SVCALLPENDED: SVCall pending\n");
  if (m33_hw->shcsr & M33_SHCSR_BUSFAULTPENDED_BITS) printf("  BUSFAULTPENDED: BusFault exception pending.\n");
  if (m33_hw->shcsr & M33_SHCSR_MEMFAULTPENDED_BITS) printf("  MEMFAULTPENDED: MemManage exception pending\n");
  if (m33_hw->shcsr & M33_SHCSR_USGFAULTPENDED_BITS) printf("  USGFAULTPENDED: UsageFault exception pending\n");
  if (m33_hw->shcsr & M33_SHCSR_SYSTICKACT_BITS) printf("  SYSTICKACT: SysTick exception active\n");
  if (m33_hw->shcsr & M33_SHCSR_PENDSVACT_BITS) printf("  PENDSVACT: PendSV exception active\n");
  if (m33_hw->shcsr & M33_SHCSR_MONITORACT_BITS) printf("  MONITORACT: Debug monitor active\n");
  if (m33_hw->shcsr & M33_SHCSR_SVCALLACT_BITS) printf("  SVCALLACT: SVCall active\n");
  if (m33_hw->shcsr & M33_SHCSR_NMIACT_BITS) printf("  NMIACT: NMI exception active state\n");
  if (m33_hw->shcsr & M33_SHCSR_USGFAULTACT_BITS) printf("  USGFAULTACT: UsageFault exception active\n");
  if (m33_hw->shcsr & M33_SHCSR_HARDFAULTACT_BITS) printf("  HARDFAULTACT: HardFault exception active\n");
  if (m33_hw->shcsr & M33_SHCSR_BUSFAULTACT_BITS) printf("  BUSFAULTACT: BusFault exception active\n");
  if (m33_hw->shcsr & M33_SHCSR_MEMFAULTACT_BITS) printf("  MEMFAULTACT: MemManage exception active\n");

  // MMFSR - memory management fault Status register 0xE000ED28
  if (m33_hw->cfsr & M33_CFSR_MMFSR_BITS)
    printf("MMFSR = 0x%02" PRIx32 " (MemManage fault status register)\n", (m33_hw->cfsr & M33_CFSR_MMFSR_BITS) >> M33_CFSR_MMFSR_LSB);
  if (m33_hw->cfsr & 1u << 7) printf("  MMARVALID: MMFAR holds a valid fault address\n");
  if (m33_hw->cfsr & 1u << 5) printf("  MLSPERR: MemManage fault occurred during floating-point lazy state preservation\n");
  if (m33_hw->cfsr & 1u << 4) printf("  MSTKERR: stacking for an exception entry has caused one or more access violations\n");
  if (m33_hw->cfsr & 1u << 3) printf("  MUNSTKERR: unstack for an exception return has caused one or more access violations\n");
  if (m33_hw->cfsr & 1u << 1) printf("  DACCVIOL: attempt to load/store at location that does not permit the operation\n");
  if (m33_hw->cfsr & 1u << 0) printf("  IACCVIOL: attempted an instruction fetch from location that does not permit execution\n");

  // BFSR - bus fault status register 0xE000ED29
  if (m33_hw->cfsr) printf("CFSR  = 0x%08" PRIx32 " (BusFault status register)\n", m33_hw->cfsr);
  if (m33_hw->cfsr & M33_CFSR_BFSR_BFARVALID_BITS) printf("  BFARVALID: BFAR holds a valid fault address\n");
  if (m33_hw->cfsr & M33_CFSR_BFSR_LSPERR_BITS)
    printf("  LSPERR: bus fault occurred during floating-point lazy state preservation\n");
  if (m33_hw->cfsr & M33_CFSR_BFSR_STKERR_BITS)
    printf("  STKERR: stacking for an exception entry has caused one or more BusFaults\n");
  if (m33_hw->cfsr & M33_CFSR_BFSR_UNSTKERR_BITS)
    printf("  UNSTKERR: unstack for an exception return has caused one or more BusFaults\n");
  if (m33_hw->cfsr & M33_CFSR_BFSR_IMPRECISERR_BITS) printf("  IMPREISERR: imprecise data access violation\n");
  if (m33_hw->cfsr & M33_CFSR_BFSR_PRECISERR_BITS)
    printf("  PRECISERR: PC value stacked for the exception return points to the instruction that caused fault\n");
  if (m33_hw->cfsr & M33_CFSR_BFSR_IBUSERR_BITS) printf("  IBUSERR: instruction bus error\n");

  // UFSR - usage fault status register
  if (m33_hw->cfsr & M33_CFSR_UFSR_DIVBYZERO_BITS) printf("  DIVBYZERO: executed an SDIV or UDIV with a divisor 0\n");
  if (m33_hw->cfsr & M33_CFSR_UFSR_UNALIGNED_BITS) printf("  UNALIGNED: unaligned memory access\n");
  if (m33_hw->cfsr & M33_CFSR_UFSR_STKOF_BITS) printf("  STKOF: stack overflow error has occurred\n");
  if (m33_hw->cfsr & M33_CFSR_UFSR_NOCP_BITS) printf("  NOCP: attempt to access a coprocessor\n");
  if (m33_hw->cfsr & M33_CFSR_UFSR_INVPC_BITS)
    printf("  INVPC: attempted an illegal load of EXC_RETURN to the PC (either invalid context or an invalid EXC_RETURN value)\n");
  if (m33_hw->cfsr & M33_CFSR_UFSR_INVSTATE_BITS)
    printf("  INVSTATE: attempt to execute instruction that makes illegal use of the EPSR\n");
  if (m33_hw->cfsr & M33_CFSR_UFSR_UNDEFINSTR_BITS) printf("  UNDEFINSTR: attempt to execute an undefined instruction\n");

  // HFSR - hard fault status register 0xE000ED2C
  if (m33_hw->hfsr) printf("HFSR  = 0x%08" PRIx32 " (HardFault status register)\n", m33_hw->hfsr);
  if (m33_hw->hfsr & M33_HFSR_DEBUGEVT_BITS) printf("  DEBUGEVT: hard fault caused by debug event\n");
  if (m33_hw->hfsr & M33_HFSR_FORCED_BITS)
    printf("  FORCED: forced hard fault escalation caused by bus/memory-management/usage fault\n");
  if (m33_hw->hfsr & M33_HFSR_VECTTBL_BITS) printf("  VECTTBL: hard fault caused by failed vector-table read\n");

  // concrete MMFAR and BFAR addresses
  if (m33_hw->cfsr & 1u << 7) printf("MMFAR = 0x%08" PRIx32 " memory fault address\n", m33_hw->mmfar);
  if (m33_hw->cfsr & M33_CFSR_BFSR_BFARVALID_BITS) printf("BFAR  = 0x%08" PRIx32 " bus fault address\n", m33_hw->bfar);

  // AFSR - auxilarity fault status register
  const uint32_t afsr = { *(volatile uint32_t *)0xE000ED3C };
  if (0 != afsr) printf("AFSR = 0x%08" PRIx32 "\n", afsr);

  printf("C%dE HardFault handler: waiting for debugger ...\n", get_core_num());

  fflush(stdout);

  if (m33_hw->dhcsr & M33_DHCSR_C_DEBUGEN_BITS) __breakpoint();   // if debugger attached
  while (true) { }
}

[[noreturn]]
__attribute__((naked)) void isr_hardfault(void)
{
  __asm volatile("tst lr, #4                         \n"   // Bit 2 selects the stack active before the exception.
                 "ite eq                             \n"
                 "mrseq r0, msp                      \n"   // Pass the original exception frame as argument 0.
                 "mrsne r0, psp                      \n"
                 "ldr r2, =0xd0000000               \n"   // SIO CPUID register; contains 0 or 1.
                 "ldr r2, [r2]                       \n"
                 "ldr r3, =hardfault_stacks          \n"
                 "add.w r3, r3, r2, lsl #10         \n"    // Select this core's 1024-byte stack.
                 "msr msplim, r3                     \n"   // Move the guard before changing MSP.
                 "add.w r3, r3, #1024                \n"
                 "msr msp, r3                        \n"
                 "b the_real_fault_handler_c         \n");
}
