name: CMake Build
on:
  push:
    paths:
      - "**"
      - "!**.md"
      - "!**license"
      - "!**.gitignore"
      - "!**.clang-format"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/build.yaml"
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "!**license"
      - "!**.gitignore"
      - "!**.clang-format"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/build.yaml"

env:
  PICO_SDK_VERSION: 2.3.0
  PICO_SDK_REL_CHECKOUT_PATH: pico-sdk
  PICO_SDK_PATH: ${{github.workspace}}/pico-sdk

  REPO_REL_CHECKOUT_PATH: target-repo
  REPO_PATH: ${{github.workspace}}/target-repo

jobs:
  cmake-build:
    name: CMake build on ${{ matrix.os }}
    runs-on: ubuntu-latest
    container: ${{ fromJSON(matrix.container) }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            container: "null"
            prerequisites: src/scripts/install-prerequisites-ubuntu.sh
          - os: archlinux-latest
            container: '{"image":"archlinux:latest"}'
            prerequisites: src/scripts/install-prerequisites-archlinux.sh
    
    steps:

      - name: "container: bootstrap"
        if: matrix.os == 'archlinux-latest'
        run: pacman -Syu --noconfirm --needed git python

      - name: "pico-sdk: cache restore"
        id: cache-picosdk-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{env.PICO_SDK_PATH}}
          key: pico-sdk-${{env.PICO_SDK_VERSION}}-${{matrix.os}}

      - name: "pico-sdk: checkout"
        if: steps.cache-picosdk-restore.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: ${{env.PICO_SDK_VERSION}}
          submodules: true
          path: ${{env.PICO_SDK_REL_CHECKOUT_PATH}}

      - name: "pico-sdk: cache store"
        id: cache-picosdk-save
        if: steps.cache-picosdk-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{env.PICO_SDK_PATH}}
          key: ${{steps.cache-picosdk-restore.outputs.cache-primary-key}}

      - name: "repository: checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ${{env.REPO_REL_CHECKOUT_PATH}}

      - name: "build: prerequisites"
        working-directory: ${{env.REPO_PATH}}
        run: ${{ matrix.prerequisites }}

      - name: "build: create build env + CMake"
        working-directory: ${{env.REPO_PATH}}
        run: src/scripts/cmake.sh

      - name: "build: make"
        working-directory: ${{env.REPO_PATH}}
        run: |
          src/scripts/make.sh
          src/scripts/picotool-info.sh
