name: Build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

env:
  BUILD_TYPE: Release

jobs:
  
  build:
    name: CMake Build
    runs-on: [ubuntu-latest]
    
    steps:

    - name: pico-sdk: cache
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/pico-sdk
        key: ${{ runner.os }}-picosdk-${{ hashFiles('${{github.workspace}}/pico-sdk/**') }}
        restore-keys: |
          ${{ runner.os }}-picosdk-

     - name: pico-sdk: checkout
        working-directory: ${{github.workspace}}
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: 2.0.0
          path: pico-sdk

    - name: submodules: checkout
       working-directory: ${{github.workspace}}/pico-sdk
       run: |
         git submodule update --init --recursive --recommend-shallow --single-branch --verbose
         git submodules status
         echo "PICO_SDK_PATH=${{github.workspace}}/pico-sdk" >> $GITHUB_ENV
        
    - name: build prerequisites
        run: |
          sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
        
    - name: checkout repository
      uses: actions/checkout@v3

    - name: checkout submodules
      run: src/scripts/git-submodules-init.sh

    - name: create build environment and run CMake
      run: src/scripts/cmake.sh

    - name: build
      run: src/scripts/cmake.sh
