name: CMake Build
on:
  push:
    branches:
    paths:
      - "**"
      - "!**.md"
      - "!**license"
      - "!**.gitignore"
      - "!**.clang-format"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/cmake.yaml"
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "!**license"
      - "!**.gitignore"
      - "!**.clang-format"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/cmake.yml.yaml"

env:
  PICO_SDK_REL_CHECKOUT_PATH: pico-sdk
  PICO_SDK_PATH: ${{github.workspace}}/pico-sdk

  REPO_REL_CHECKOUT_PATH: target-repo
  REPO_PATH: ${{github.workspace}}/target-repo

jobs:
  cmake-build:
    name: CMake build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    
    steps:
      - name: "pico-sdk: checkout"
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: 2.0.0
          submodules: true
          path: ${{env.PICO_SDK_REL_CHECKOUT_PATH}}

      - name: "repository: checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ${{env.REPO_REL_CHECKOUT_PATH}}

      - name: "build prerequisites"
        working-directory: ${{env.REPO_PATH}}
        run: src/scripts/install-prerequisites-ubuntu.sh

      - name: "build: create build env + CMake"
        working-directory: ${{env.REPO_PATH}}
        run: src/scripts/cmake.sh

      - name: "build: make"
        working-directory: ${{env.REPO_PATH}}
        run: |
          src/scripts/make.sh
          src/scripts/picotool-info.sh
